set(LIB_INCLUDES)

set(LINK_LIBRARIES)

# Build up a list of sources and libraries to link with
set(OpenGL_GL_PREFERENCE "LEGACY")
find_package(OpenGL REQUIRED)
find_package(GLEW REQUIRED)
if(GLEW_FOUND)
    list(APPEND LIB_INCLUDES ${GLEW_INCLUDE_DIRS})
    list(APPEND LINK_LIBRARIES ${GLEW_LIBRARIES})
endif()
find_package(glm REQUIRED)
if(GLM_FOUND)
    list(APPEND LIB_INCLUDES ${GLM_INCLUDE_DIRS})
    list(APPEND LINK_LIBRARIES ${GLM_LIBRARIES})
endif()
find_package(SDL2 REQUIRED)
if(SDL2_FOUND)
    list(APPEND LIB_INCLUDES ${SDL2_INCLUDE_DIRS})
    list(APPEND LINK_LIBRARIES ${SDL2_LIBRARIES})
endif()
find_package(ASSIMP REQUIRED)
if(ASSIMP_FOUND)
    list(APPEND LIB_INCLUDES ${ASSIMP_INCLUDE_DIRS})
    list(APPEND LINK_LIBRARIES ${ASSIMP_LIBRARIES})
endif()
find_library(UUID_LIBRARY NAMES uuid)
if(UUID_FOUND)
    list(APPEND LIB_INCLUDES ${UUID_INCLUDE_DIRS})
    list(APPEND LINK_LIBRARIES ${UUID_LIBRARIES})
endif()
find_package(fmt REQUIRED)
if(fmt_FOUND)
    list(APPEND LIB_INCLUDES ${fmt_INCLUDE_DIRS})
    list(APPEND LINK_LIBRARIES ${fmt_LIBRARIES})
endif()
find_package(SOIL REQUIRED)
if(SOIL_FOUND)
    list(APPEND LIB_INCLUDES ${SOIL_INCLUDE_DIRS})
    list(APPEND LINK_LIBRARIES ${SOIL_LIBRARIES})
endif()
# ----------------------------------- IMGUI ------------------------------------
# Add the ImGui library
set(IMGUI_DIR ${PROJECT_PATH}/imgui)
file(GLOB IMGUI_SOURCES ${IMGUI_DIR}/*.cpp ${IMGUI_DIR}/*.h)
add_library(imgui ${IMGUI_SOURCES})
# Assuming you're using OpenGL3 and glfw3 for imgui's backends
add_library(imgui-sdl2-opengl3 
    ${IMGUI_DIR}/backends/imgui_impl_sdl2.cpp 
    ${IMGUI_DIR}/backends/imgui_impl_opengl3.cpp
)
list(APPEND LIB_INCLUDES imgui PUBLIC ${IMGUI_DIR} ${IMGUI_DIR}/backends)